### ISSUE TITLE
another problem in line 201

### ISSUE THREAD

**Issue by guoChopper** [CaiJingLong/flutter_vertical_marquee#6]
It repeats when you scroll to the next row

**Comment by loveRose** [comment]
我的也是有问题，滚动的过程中，下一行显示的仍然是当前行数据，只有当滚动完成之后才一瞬间编程下一行的数据，然后重复这个过程，分别扭～～～

**Comment by CaiJingLong** [comment]
Sorry, I haven't had time to do this recently.
If possible, please open PR to help me , or wait a few days.
